### ISSUE TITLE
Support fine-tuning of template query creation

### ISSUE THREAD

**Issue by jakubplichta** [jakubplichta/grafana-dashboard-builder#10]
Currently template query use `*` for searching variable values. It would be nice to allow customization

```yaml
  templates:
    - query:
        query: '{metric-prefix}.{component}.$application'
        application:
          metric: '*core*'
          current: first
          options:
            - first
            - last
```
