### ISSUE TITLE
Placeholder {name} is not resolved in text/content

### ISSUE THREAD

**Issue by jaceksan** [jakubplichta/grafana-dashboard-builder#101]
Below you can find example code.
In panel **text**, attribute **content**, if value contains variable defined in --config file, it is not resolved.

- config file rack-na1.yaml (--config)
```
context:
  elastic-host: "myhost.com"
```
- dashboard file vertica.yaml
```
- name: notice-documentation
  rows:
    - row:
        title: Documentation
        panels:
          - text:
              mode: markdown
              content: "Link to [Main Dashboard](https://{elastic-host}/xxxxx)"
```

**Comment by jakubplichta** [comment]
@jaceksan you need to pass variables down - context defined through `--config` is not accessible from everywhere and only on dashboard level. If you need to use it in named component then your yaml will need to look like this:

```yaml
- name: 'dashboard'
  dashboard:
    rows:
      - notice-documentation:
          elastic-host: '{elastic-host}'

- name: notice-documentation
  rows:
    - row:
        title: Documentation
        panels:
          - text:
              mode: markdown
              content: "Link to [Main Dashboard](https://{elastic-host}/xxxxx)"
```
