### ISSUE TITLE
Grafana 4.5 - definition of X/Y axes is too complicated

### ISSUE THREAD

**Issue by jaceksan** [jakubplichta/grafana-dashboard-builder#120]
- Old way
```yaml
y_formats: [s, short]
```
- (Current) new way
```yaml
yaxes:
  - yaxis:
      format: decmbytes
  - yaxis:
      format: decmbytes
xaxes:
  show: true
  format: time
```

I expect the following:
- Second Y axis defaults to first one, if it is not needed
`show=true` is mandatory + same format 
- X axis defaults to `show=true` and `format=time`
