### ISSUE TITLE
Add support for panel type "dashlist"

### ISSUE THREAD

**Issue by jaceksan** [jakubplichta/grafana-dashboard-builder#128]
There is new type of panel in "new" Grafana versions - "dashlist".
It is quite handy for crossroad use case.
In multiple rows / columns it displays list of dashboard names being links to these dashboards.
Dashboards are included using search or list of tags.
Also there is special type of dashlist displaying recently viewed dashboards.
Here is example JSON code:
```yaml
  "rows": [
    {
      "panels": [
        {
          "headings": true,   # turn on headers on each 
          "limit": 20,             # do not display more than limit
          "span": 6,              # If more panels are in the same row
          "query": "",            # search dashboards using this query
          "recent": false,      # show recently viewed
          "search": true,       # turn on search
          "starred": false,     # display only starred
          "tags": [                 # search using tags
            "vertica_overview"
          ],
          "title": "Overview dashboards",
          "type": "dashlist"
       },
```
