### ISSUE TITLE
Support "include All" option for custom template

### ISSUE THREAD

**Issue by manueligno78** [jakubplichta/grafana-dashboard-builder#149]
includeAll flag is not working properly.
YAML snippet:
```
...
    - custom-template:
        name: service
        options: 
          - option 1
          - option 2
        includeAll: true
        multi: true
        current: All
...
```

This is the output:
```
...
      {
        "current": {
          "text": "All",
          "value": "All"
        },
        "datasource": null,
        "includeAll": true,
        "multi": true,
        "name": "service",
        "options": [
          {
            "text": "option 1",
            "value": "option 1"
          },
          {
            "text": "option 2",
            "value": "option 2"
          }
        ],
        "query": "option 1,option 2",
        "refresh": 0,
        "refresh_on_load": false,
        "type": "custom"
      }
...
```

Output should be:
```
...
        "current": {
          "tags": [],
          "text": "All",
          "value": "$__all"
        },
        "datasource": null,
        "hide": 0,
        "includeAll": true,
        "label": "",
        "multi": false,
        "name": "service",
        "options": [
          {
            "selected": true,
            "text": "All",
            "value": "$__all"
          },
...
```
