### ISSUE TITLE
Use yaml components from different files

### ISSUE THREAD

**Issue by manueligno78** [jakubplichta/grafana-dashboard-builder#153]
Actually this is a question, with a new sample request.

I am struggling to understand how to have two yaml files, one with my project definition and one with some variables that I want to reuse also in other projects.

I know that you can run grafana-dashboard-builder passing a folder to path parameter. And It works, but I cannot still create a reference between the two files... I'll try to explain better.

What I want to do is this:

Given a project file like this: 
```
---
- name: test Project Dashboards
  project:
    service:
      - service1
      - service2
      - service3
    dashboards:
      - TestDashboard

- name: TestDashboard
  dashboard:
    title: 'TestDashboard'
...
    templates:
    - custom-template:
        name: service
        options: '{service}'
        includeAll: true
        multi: true
        current: All
...
```

I want to remove the list from project file and move it to another file (services.yaml), because I would like to reuse the same list on other dashboards/projects

Can you help me to understand?
