### ISSUE TITLE
Resolving of 2level refereces in properties is not working

### ISSUE THREAD

**Issue by jakubplichta** [jakubplichta/grafana-dashboard-builder#3]
```yaml
- name: Example project
  project:
    p1: MyApp
    p2: '{p1}'
    p3: '{p2}'
```
