### ISSUE TITLE
Add support for passing list of params to dashboard-link params

### ISSUE THREAD

**Issue by matejhasul** [jakubplichta/grafana-dashboard-builder#61]
Singlestat template:
```yaml
- name: singlestat-{title}
  panels:
    - single-stat:
        title: '{title}'
        error: false
        span: 4
        sparkline:
          show: false
          full: false
          lineColor: "rgb(31, 120, 193)"
          fillColor: "rgba(31, 118, 189, 0.18)"
        valueMaps:
          'null': '{title}'
        links:
          - dashboard-link:
              title: '{title}'
              dashboard: '{dashboard}'
              params: '{params}'
```
Dashboard definition:
```yaml
      - row:
          title: 'Zendesk4'
          height: '250px'
          editable: true
          collapse: true
          panels:
            - singlestat-{title}:
                title:
                  - Zendesk4 connector overview:
                      dashboard: 'Zendesk4 Connector Overview'
                  - Zendesk4 connector resources:
                      dashboard: 'ATeam - connectors zendesk4 resources'
                      params:
                        - cluster: 51
                        - node: 'na1-connectors-www01'
```
