### ISSUE TITLE
Create custom template from variable

### ISSUE THREAD

**Issue by t-8ch** [jakubplichta/grafana-dashboard-builder#64]
It seems at the moment it is impossible to create a custom template variable in the dashboard from a variable defined in the builder yaml file.

**Comment by jakubplichta** [comment]
@t-8ch can you please provide example of what you are trying to accomplish? Thanks!

**Comment by t-8ch** [comment]
@jakubplichta
This works:


```yaml
- name: 'some template'
  templates:
    - custom:
        - name: 'var'
          options:
            - a
            - b
```

What I would like to use:
```yaml
- name: 'some dashboard'
  dashboard:
    - templates:
      - another-template:
          choices: '{nodes}'
    # actually this would get passed down from further up in my case
    nodes:
      - x
      - y

- name: 'another-template'
  templates:
    - custom:
        - name: 'choice'
          options: '{choices}'
```
