### ISSUE TITLE
Allow placeholders in component names

### ISSUE THREAD

**Issue by jakubplichta** [jakubplichta/grafana-dashboard-builder#9]
```yaml
- name: rows
  rows:
    - '{param}-row':
        param:
          - value1
          - value2

- name: '{param}-row'
  rows:
    - row:
        title: '{param} row'
```
